### ISSUE TITLE
How to host a custom track from URL?

### ISSUE THREAD

**Issue by SJacobs501** [gro-ove/ac-server-wrapper#5]
content.json:

```
{
  "track": { 
	"big_nordschleife": {			        	
		"url": "https://drive.google.com/file/d/0B3tZt207m0j2U1MwcXFDdjRjZ3c/view?usp=drivesdk" 
	}
  }
}
```

This is when I try to install the missing content, how come?

![b64ae8aec2dfa5b72ea11d1c79d181f5](https://user-images.githubusercontent.com/29664667/27911830-d7e49846-625a-11e7-9f06-82b7e0b386c4.png)

The server running:

![55f541e3080ca1376676113b2bb522cc](https://user-images.githubusercontent.com/29664667/27911870-fc0a2e84-625a-11e7-996b-b211ca7eb6a2.png)

Also, why does pressing the missing content link to assetto-db.com? Shouldn't they be directing to the google drive links?

**Comment by gro-ove** [comment]
Again, here is [another example preset](https://drive.google.com/file/d/0B6GfX1zRa8pOT3pmbVFVdnk3SUU/view), with a custom layout of Highlands made by Topuz.

Also, you don’t need to specify track ID in “content.json”, since there is only one track per server — CM (or, in theory, any other client) will know it anyway.
